on:
  create:
    tags: '*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Build
      run: docker build --output . .
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        name: PrusaSlicer ${{ github.ref_name }}
        body: This is a static build of PrusaSlicer ${{ github.ref_name }} for Debian Stable.
        make_latest: true
        files: '*.tar.xz'
